### ISSUE TITLE
Relay calls to core-service through the gateway 

### ISSUE THREAD

**Issue by ableuler** [SwissDataScienceCenter/renku-gateway#180] opened 2019-11-26 20:15 UTC
The new Renku repository service will need to be exposed through the gateway. My suggestion would be to expose it as `/api/repository/...` which will result in API endpoints such as 
```
https://renkulab.io/api/repository/cache/project-clone
```
To serve such requests, the repository service will need access to the gitlab oauth access token and some user information:
```
Renku-user-id: 9af6abce-bd63-48e4-a0c7-233a8c524e48
Renku-user-fullname: Andreas Bleuler
Renku-user-email: andi@example.com
Authorization: Bearer db6d049ec8f3c225c248fe6f3caddbd47c948edb22e6b83b37cc08d79b264ca1
```
All these will be added to dedicated header fields by the gateway before forwarding the request.

The repository URL (containing gitlab namespace and project name) will be provided by the client as part of the request body:
```
{
  "project_url": "https://dev.renku.ch/gitlab/andreas/coffee-machine"
}
```

**Comment by rokroskar** [comment] 2019-11-26 20:22
This LGTM - cc @vfried @lorenzo-cavazzi @ciyer @jsam @jachro

**Comment by lorenzo-cavazzi** [comment] 2019-11-27 10:22
Looks good!
Only one minor detail: my understanding is that the new service will be used to serve several resources, not only repository related data. Would it makes sense to use a different url than `/api/repository/`? Maybe `/api/renku/`?

**Comment by jachro** [comment] 2019-11-28 07:55
I've also got some mixed feelings about the `cache` segment in the URL. I have to say I wasn't really following the Renku Service development but I thought, as it supposed to be a facade of Renku CLI, the URL will become smth like `https://renkulab.io/api/renku/<namespace>/<name>` with body specifying the command and all the other details depending on the command. That's with an assumption that the command resolving will happen on the new service side internally. The other option would be to have `https://renkulab.io/api/renku/<namespace>/<name>/<command>` so then we'd have a nice REST API for all the commands. The problem is that I'm not so sure if that's the proper issue to raise my concerns as in regards to the Gateway part enriching the Headers looks absolutely fine to me.

**Comment by rokroskar** [comment] 2019-11-28 08:02
That suggestion makes sense to me, since essentially every command needs to relate to the namespace and project. It requires the service to be aware of the specific gitlab instance, but I suppose that's fine for now.

**Comment by rokroskar** [comment] 2019-11-28 23:01
After some discussion today the consensus seems to be to not mix REST and rpc APIs. At the moment, the endpoints are served from `/api/core` but I like @lorenzo-cavazzi's suggestion that it could be `/api/renku` instead. @jsam what do you think?

**Closed** 2020-01-09 10:15 UTC
