### ISSUE TITLE
Gateway to forward requests to KG endpoints

### ISSUE THREAD

**Issue by jachro** [SwissDataScienceCenter/renku-gateway#300] opened 2020-09-29 15:43 UTC
As a Renku user, I'd like HTTP requests to certain Renku APIs to be authenticated and forwarded to a relevant internal Renku service.

**Acceptance criteria:**
* Gateway to expose new APIs forwarding requests to relevant endpoints on the knowledge-graph service;
  * the endpoints to authenticate the caller by validating the request cookie;
  * the endpoints to exchange the validated cookie to user's GitLab Access Token and its GitLab User Id and pass them in the request headers `Authorization: Bearer <GitLab Access Token>` to the knowledge-graph endpoints (I thought we took some decisions about custom headers naming patterns but I couldn't dig that out anywhere);
  * the initial APIs could be mapped as follows:
  
    | Gateway | Knowledge Graph |
    |----------|-------------------|
    | GET /api/datasets  | GET /knowledge-graph/datasets |
    | GET /api/datasets/:id | GET /knowledge-graph/datasets/:id |
    | GET /api/projects/:group1/:group2/.../:groupX/:name | GET /knowledge-graph/projects/:group1/:group2/.../:groupX/:name |
    | GET /api/projects/:group1/:group2/.../:groupX/:name/datasets | GET /knowledge-graph/projects/:group1/:group2/.../:groupX/:name/datasets |
    | POST /graphql | POST /knowledge-graph/graphql |

  * the endpoints to allow a caller without a cookie to reach KG endpoints as it can be requesting info about public data.

**Comment by rokroskar** [comment] 2020-10-07 09:00
duplicate of #179?

**Comment by ableuler** [comment] 2021-01-27 07:58
> the endpoints to allow a caller without a cookie to reach KG endpoints as it can be requesting info about public data.

The idea here is to still forward the call, but without adding the corresponding headers. Then it's the business of the KG to decide what information can be returned to this unauthenticated call.

**Comment by ableuler** [comment] 2021-01-27 07:59
> * to user's GitLab Access Token and its GitLab User Id and pass them in the request headers `Authorization: Bearer <GitLab Access Token>`, `x-gitlab-user-id: <GitLab User Id>`to the

@jachro Are those the same for all KG endpoints?

**Comment by jachro** [comment] 2021-01-27 11:12
> > the endpoints to allow a caller without a cookie to reach KG endpoints as it can be requesting info about public data.
> 
> The idea here is to still forward the call, but without adding the corresponding headers. Then it's the business of the KG to decide what information can be returned to this unauthenticated call. Does that sound ok @jachro?

Exactly that. We'd simply return info about public projects/datasets/etc

**Comment by jachro** [comment] 2021-01-27 11:15
> > * to user's GitLab Access Token and its GitLab User Id and pass them in the request headers `Authorization: Bearer <GitLab Access Token>`, `x-gitlab-user-id: <GitLab User Id>`to the
> 
> @jachro Are those the same for all KG endpoints?

Yes, all endpoints work the same way when it comes to the security-related headers.

**Comment by jachro** [comment] 2021-01-27 11:16
> duplicate of #179?

@rokroskar yes and no :) I believe we will come back to the `file` resource at some point...

**Comment by lorenzo-cavazzi** [comment] 2021-02-25 16:45
As discussed offline, the suggested routing would conflict with the current routing for the GitLab API.
A simple solution would be adding a prefix to all the KG routes (e.g. `/api/kg`) as we are already doing for the core service with `/api/renku`.
This would simplify the rules and prevent any conflict. We can revise it later when we have a single point of access for the resources -- all the queries for projects would then go through `/api/projects`, or even only `/projects`.

**Comment by rokroskar** [comment] 2021-03-01 10:50
@lorenzo-cavazzi please keep in mind also https://github.com/SwissDataScienceCenter/renku-gateway/issues/169 - in fact maybe this issue needs to be added to that epic.

**Comment by lorenzo-cavazzi** [comment] 2021-03-01 13:06
I'm not sure if this issue has an impact on that epic since it's mainly about adding the GitLab tokens and the missing routes.
Once we will have a single endpoint serving the content for specific entities (like datasets or project) we can easily simplify the routing and add the content-based response as tracked by #169

**Comment by ableuler** [comment] 2021-03-09 10:07
> As discussed offline, the suggested routing would conflict with the current routing for the GitLab API.
> A simple solution would be adding a prefix to all the KG routes (e.g. `/api/kg`) as we are already doing for the core service with `/api/renku`.
> This would simplify the rules and prevent any conflict. We can revise it later when we have a single point of access for the resources -- all the queries for projects would then go through `/api/projects`, or even only `/projects`.

hmm, I was hoping we could move a small step towards having an actual Renku REST api. But I agree, we have to solve the bigger issue (having dedicated services per top-level resource) first.

**Closed** 2021-03-09 12:49 UTC
Labels: enhancement
